In [3]:
import pandas as pd

## Reading the files

In [4]:
df = pd.read_csv('data1.csv')

FileNotFoundError: [Errno 2] No such file or directory: 'data1.csv'

In [ ]:
df

         date       city  temperature  humidity condition
0  01-01-2025   hyderbad          NaN        32     sunny
1  02-01-2025   hyderbad         30.0        29      cold
2  03-01-2025   hyderbad         33.0        27       NaN
3  04-01-2025   hyderbad         34.0        29    cloudy
4  05-01-2025   hyderbad          NaN        33     rainy
5  06-01-2025  bangalore         28.0        32     rainy
6  07-01-2025  bangalore         32.0        29     sunny
7  08-01-2025  bangalore         29.0        29       NaN
8  09-01-2025  bangalore          NaN        31     rainy
9  10-01-2025  bangalore         28.0        32    sunnyu

In [ ]:
df.isnull()

    date   city  temperature  humidity  condition
0  False  False         True     False      False
1  False  False        False     False      False
2  False  False        False     False       True
3  False  False        False     False      False
4  False  False         True     False      False
5  False  False        False     False      False
6  False  False        False     False      False
7  False  False        False     False       True
8  False  False         True     False      False
9  False  False        False     False      False

## Exploring the data

In [ ]:
df.tail()

         date       city  temperature  humidity condition
5  06-01-2025  bangalore           28        32     rainy
6  07-01-2025  bangalore           32        29     sunny
7  08-01-2025  bangalore           29        29    cloudy
8  09-01-2025  bangalore           31        31     rainy
9  10-01-2025  bangalore           28        32    sunnyu

In [ ]:
df.head()

         date      city  temperature  humidity condition
0  01-01-2025  hyderbad          NaN        32     sunny
1  02-01-2025  hyderbad         30.0        29      cold
2  03-01-2025  hyderbad         33.0        27       NaN
3  04-01-2025  hyderbad         34.0        29    cloudy
4  05-01-2025  hyderbad          NaN        33     rainy

In [ ]:
df['temperature']=df['temperature'].fillna(df['temperature'].mean())
df

         date       city  temperature  humidity condition
0  01-01-2025   hyderbad    30.571429        32     sunny
1  02-01-2025   hyderbad    30.000000        29      cold
2  03-01-2025   hyderbad    33.000000        27       NaN
3  04-01-2025   hyderbad    34.000000        29    cloudy
4  05-01-2025   hyderbad    30.571429        33     rainy
5  06-01-2025  bangalore    28.000000        32     rainy
6  07-01-2025  bangalore    32.000000        29     sunny
7  08-01-2025  bangalore    29.000000        29       NaN
8  09-01-2025  bangalore    30.571429        31     rainy
9  10-01-2025  bangalore    28.000000        32    sunnyu

In [ ]:
df['humidity']=df['humidity'].fillna(df['humidity'].sum())

In [ ]:
df

         date       city  temperature  humidity condition
0  01-01-2025   hyderbad    30.571429        32     sunny
1  02-01-2025   hyderbad    30.000000        29      cold
2  03-01-2025   hyderbad    33.000000        27       NaN
3  04-01-2025   hyderbad    34.000000        29    cloudy
4  05-01-2025   hyderbad    30.571429        33     rainy
5  06-01-2025  bangalore    28.000000        32     rainy
6  07-01-2025  bangalore    32.000000        29     sunny
7  08-01-2025  bangalore    29.000000        29       NaN
8  09-01-2025  bangalore    30.571429        31     rainy
9  10-01-2025  bangalore    28.000000        32    sunnyu

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   date         10 non-null     object
 1   city         10 non-null     object
 2   temperature  10 non-null     float64
 3   humidity     10 non-null     int64
 4   condition    8 non-null      object
dtypes: float64(1), int64(1), object(3)
memory usage: 532.0+ bytes

In [ ]:
df.shape

(10, 5)

In [ ]:
df.columns

Index(['date', 'city', 'temperature', 'humidity', 'condition'], dtype='object')

In [ ]:
df.index

RangeIndex(start=0, stop=10, step=1)

In [ ]:
df.dtypes

date            object
city            object
temperature    float64
humidity         int64
condition       object
dtype: object

In [ ]:
df.city

0     hyderbad
1     hyderbad
2     hyderbad
3     hyderbad
4     hyderbad
5    bangalore
6    bangalore
7    bangalore
8    bangalore
9    bangalore
Name: city, dtype: object

In [ ]:
df.date

0    01-01-2025
1    02-01-2025
2    03-01-2025
3    04-01-2025
4    05-01-2025
5    06-01-2025
6    07-01-2025
7    08-01-2025
8    09-01-2025
9    10-01-2025
Name: date, dtype: object

In [ ]:
df['city'][df['condition']=='sunny']

0     hyderbad
6    bangalore
Name: city, dtype: object

## Creating the dataset

In [5]:
df = pd.DataFrame({
    "name":[ "Surya", "Kumar", "Anil", "Ravi", "Suresh","Mahesh", "Rohit", "Amit", "Vijay", "Arjun"],
    "age": [15, 23, 28 , 0,27,26, 24, 29, 31, 22]
})

In [ ]:
df.isnull()

    name    age
0  False  False
1  False  False
2  False  False
3  False  False
4  False  False
5  False  False
6  False  False
7  False  False
8  False  False
9  False  False

In [6]:
df.head()

     name  age
0   Surya   15
1   Kumar   23
2    Anil   28
3    Ravi    0
4  Suresh   27

In [7]:
df.tail()

     name  age
5  Mahesh   26
6   Rohit   24
7    Amit   29
8   Vijay   31
9   Arjun   22

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    10 non-null     object
 1   age     10 non-null     int64
dtypes: int64(1), object(1)
memory usage: 292.0+ bytes

In [ ]:
df.shape

(10, 2)